# Generated by Django 5.0.6 on 2024-06-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_rules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationrule',
            name='publish_status_id',
        ),
        migrations.AddField(
            model_name='timeschedule',
            name='publish_status_id',
            field=models.IntegerField(default=0),
        ),
    ]
