# Generated by Django 5.0.6 on 2024-07-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_rules', '0002_remove_operationrule_publish_status_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeschedule',
            old_name='operation_rule',
            new_name='operation_rule_id',
        ),
        migrations.RenameField(
            model_name='timeschedule',
            old_name='time_schedule_detail',
            new_name='time_schedule_detail_id',
        ),
        migrations.RemoveField(
            model_name='timescheduledetail',
            name='delete_flg',
        ),
        migrations.AddField(
            model_name='timeschedule',
            name='out_of_service_flg',
            field=models.BooleanField(default=False),
        ),
    ]
