# Generated by Django 5.0.6 on 2024-07-07 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_rules', '0004_rename_operation_rule_id_timeschedule_operation_rule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_permission_name', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserEditPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_rules.editpermission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'edit_permission')},
            },
        ),
    ]
