# Generated by Django 5.0.6 on 2024-07-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_rules', '0005_editpermission_usereditpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timescheduledetail',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timescheduledetail',
            name='detail_comment',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='timescheduledetail',
            name='memo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='timescheduledetail',
            name='operation_status_detail_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timescheduledetail',
            name='operation_status_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
