# Generated by Django 5.0.6 on 2024-07-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_rules', '0006_alter_timescheduledetail_departure_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timescheduledetail',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
