# Generated by Django 5.0.6 on 2024-07-12 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_rules', '0007_alter_timescheduledetail_departure_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timescheduledetail',
            name='operation_status_detail_id',
        ),
        migrations.RemoveField(
            model_name='timescheduledetail',
            name='operation_status_id',
        ),
        migrations.AddField(
            model_name='timescheduledetail',
            name='operation_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_schedule_details', to='operation_rules.operationstatus'),
        ),
        migrations.AddField(
            model_name='timescheduledetail',
            name='operation_status_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_schedule_details', to='operation_rules.operationstatusdetail'),
        ),
    ]
