# Generated by Django 5.0.6 on 2024-07-18 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_rules', '0009_departurepoint_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeschedule',
            name='destination',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.DO_NOTHING, to='operation_rules.destination'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeschedule',
            name='publish_holiday_flg',
            field=models.BooleanField(default=False),
        ),
    ]
