# Generated by Django 5.0.6 on 2024-07-18 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_rules', '0011_remove_destination_departure_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeschedule',
            name='destination',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='operation_rules.destination'),
        ),
    ]
